id: I34300FAD
default_language: bo
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:32:24.142978
last_modified: 2023-01-04 11:32:24.142994
source_metadata:
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
bases:
  EE5B:
    title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
      of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
    base_file: EE5B.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
